Repository NLnetLabs/cascade, pull requests merged in 2025-10, with the labels that each got.

#103 Link DNSSEC to RFC 9364.
  doc/manual/source/index.rst
Labels: documentation

#101 More Quick Start edits.
  doc/manual/source/quick-start.rst
Labels: documentation

#94 WIP docs (including Quick Start)
  doc/manual/source/architecture.rst
  doc/manual/source/before-you-start.rst
  doc/manual/source/building.rst
  doc/manual/source/cascade-for-opendnssec-users.rst
  doc/manual/source/cli.rst
  doc/manual/source/hsms.rst
  doc/manual/source/importing-keys.rst
  doc/manual/source/index.rst
  doc/manual/source/installation.rst
  doc/manual/source/limitations.rst
  doc/manual/source/migration.rst
  doc/manual/source/offline-ksk.rst
  doc/manual/source/quick-start.rst
  doc/manual/source/softhsm.rst
Labels: documentation

#114 Add more context on KMIP connection & state saving errors.
  src/api.rs
  src/cli/commands/hsm.rs
  src/units/http_server.rs
Labels: bug

#123 Move zone registration till after zone addition, but before zone added processing.
  src/center.rs
Labels: bug

#143 Canonicalize zonefile path before sending it to the server, and show zonefile loading errors in cascate zone status.
  src/cli/commands/zone.rs
  src/units/zone_loader.rs
Labels: enhancement

#139 Fix blocked signing of the same zone.
  src/cli/commands/zone.rs
  src/units/zone_signer.rs
  src/zonemaintenance/types.rs
Labels: bug

#145 Replace references to rc1 with alpha and point users to the proposed repo setup.
  doc/manual/source/building.rst
  doc/manual/source/installation.rst
  doc/manual/source/softhsm.rst
  doc/manual/source/thales.rst
Labels: documentation, packaging

#146 Hint to users to make sure Cascade is running.
  doc/manual/source/quick-start.rst
Labels: documentation

#149 Name the policy 'softhsm', not 'default'.
  doc/manual/source/softhsm.rst
Labels: documentation

#150 Add missing policy reload command.
  doc/manual/source/softhsm.rst
Labels: documentation

#170 Use proposed/testing names where appropriate.
  doc/manual/source/installation.rst
Labels: documentation
